### PR TITLE
Fix #19 and update appearance

### LINKED ISSUE #19: add tracking not working
Hi There,

When I add a tracking in Aftership portal I see it back in the card.
When I add a tracking from the card it doesn't show in Aftership portal or in the card 

What can this be?

### PR DESCRIPTION
**Pull request by slinkymanbyday**
Fix #19 by adding slug parameter. 
Also slightly changed how some things appear, instead of showing tracking number, it shows the last message, feel free to change that back, but it is more helpful for when i look at it.

### CODE REVIEW

**Comment by iantrich** [comment]
Awesome 🎉

**Comment by iantrich** [comment]
@slinkymanbyday would you mind doing a PR for the Readme with an updated image showing off your changes? I don't use this integration/card anymore and don't really want to go to the trouble, so hoping you have something that can show off your work for people. Thanks.

**Comment by slinkymanbyday** [comment]
Yep, will do.
I have also realised the limits of moving to the free tier of aftership, have started building a integration and card for tracktry, which seems to be a decent free alternative (17track wasn't working too well for me)

**Comment by dddesign** [comment]
@slinkymanbyday I wonder if you have tracktry integration a card ready?! it seems that free plan of aftership has no api access anymore...

**Comment by slinkymanbyday** [comment]
@dddesign 

Custom component and card here (add through hacs)

https://github.com/slinkymanbyday/tracktry-homeassistant-custom-component

https://github.com/slinkymanbyday/tracktry-card

**Pull request merged**
